"""Recognizing test files and generated files by the conventions of their ecosystem.

Deliberately conservative: a file is only a "test" if it follows a real naming or folder
convention of pytest, Jest, Vitest, Mocha, Playwright or Cypress. Merely containing the
word "test" (latest.py, contest.ts, attestation.py, testimonials.tsx) is not enough.
"""

from __future__ import annotations

import re
from collections.abc import Iterable
from dataclasses import dataclass, field

PYTHON_EXTENSIONS = {".py", ".pyi"}
JS_EXTENSIONS = {".js", ".jsx", ".ts", ".tsx", ".mjs", ".cjs", ".mts", ".cts"}

# Folders whose contents are test code or test data, by convention.
TEST_DIRS = {"tests", "test"}  # pytest / unittest / Mocha default folders
JS_TEST_DIRS = {"__tests__", "__mocks__", "__fixtures__"}  # Jest
SNAPSHOT_DIRS = {"__snapshots__"}  # Jest, syrupy, pytest-textual-snapshot, ...

# foo.test.ts, foo.spec.jsx, foo.e2e-spec.ts (NestJS), foo.cy.ts (Cypress), test.js, spec.ts
_JS_TEST_NAME = re.compile(
    r"(?:^|\.)(?:test|spec|e2e-spec|e2e-test|cy)\.[cm]?[jt]sx?$", re.IGNORECASE
)

LOCKFILES = {
    "package-lock.json",
    "npm-shrinkwrap.json",
    "yarn.lock",
    "pnpm-lock.yaml",
    "bun.lock",
    "bun.lockb",
    "deno.lock",
    "poetry.lock",
    "uv.lock",
    "pdm.lock",
    "pipfile.lock",
    "cargo.lock",
    "gemfile.lock",
    "composer.lock",
    "go.sum",
    "flake.lock",
    "pubspec.lock",
    "mix.lock",
    "podfile.lock",
    "packages.lock.json",
}

_GENERATED_SUFFIXES = (
    ".min.js",
    ".min.mjs",
    ".min.cjs",
    ".min.css",
    ".js.map",
    ".mjs.map",
    ".cjs.map",
    ".css.map",
    ".d.ts.map",
    # protocol buffers / gRPC
    "_pb2.py",
    "_pb2.pyi",
    "_pb2_grpc.py",
    "_pb.js",
    "_pb.d.ts",
    "_pb.ts",
    "_grpc_pb.js",
    "_grpc_pb.d.ts",
    ".pb.go",
    ".pb.gw.go",
    # other code generators
    ".g.dart",
    ".freezed.dart",
    ".designer.cs",
)
_GENERATED_DIRS = {"__generated__"}  # Relay, GraphQL codegen
_GENERATED_MARKERS = re.compile(
    r"@generated|do not edit|code generated by|auto-?generated|automatically generated"
    r"|generated by (?:the )?[\w.-]+ (?:compiler|codegen|tool)",
    re.IGNORECASE,
)
HEADER_LINES = 5


def _split(path: str) -> tuple[list[str], str]:
    *dirs, name = path.split("/")
    return dirs, name


def _extension(name: str) -> str:
    dot = name.rfind(".")
    return name[dot:].lower() if dot > 0 else ""


def is_test_file(path: str) -> bool:
    dirs, name = _split(path)
    lower = name.lower()
    extension = _extension(name)
    if any(d in SNAPSHOT_DIRS or d in JS_TEST_DIRS for d in dirs):
        return True
    if extension in PYTHON_EXTENSIONS:
        stem = lower[: -len(extension)]
        if stem.startswith("test_") or stem.endswith("_test"):
            return True  # pytest's default python_files patterns
        if lower in ("conftest.py", "tests.py"):  # pytest fixtures; Django's app tests
            return True
        return any(d in TEST_DIRS for d in dirs)
    if extension in JS_EXTENSIONS:
        if _JS_TEST_NAME.search(lower):
            return True
        if lower.startswith(("setuptests.", "jest.setup.", "vitest.setup.")):
            return True
        return any(d in TEST_DIRS for d in dirs)
    if extension == ".snap":
        return True
    # Non-code files (fixtures, data) inside a test folder belong to the tests too.
    return any(d in TEST_DIRS for d in dirs)


def has_generated_header(lines: Iterable[str]) -> bool:
    for index, line in enumerate(lines):
        if index >= HEADER_LINES:
            break
        if _GENERATED_MARKERS.search(line):
            return True
    return False


def is_generated_path(path: str) -> bool:
    dirs, name = _split(path)
    lower = name.lower()
    if lower in LOCKFILES:
        return True
    if lower.endswith(_GENERATED_SUFFIXES) or ".generated." in lower:
        return True
    return any(d in _GENERATED_DIRS for d in dirs)


def _glob_to_regex(pattern: str) -> re.Pattern[str]:
    """Translate a .gitattributes pattern (gitignore-style glob) into a regex."""
    anchored = "/" in pattern.rstrip("/")
    pattern = pattern.lstrip("/")
    out = []
    i = 0
    while i < len(pattern):
        char = pattern[i]
        if pattern.startswith("**/", i):
            out.append("(?:.*/)?")
            i += 3
        elif pattern.startswith("/**", i) and i + 3 == len(pattern):
            out.append("/.*")
            i += 3
        elif pattern.startswith("**", i):
            out.append(".*")
            i += 2
        elif char == "*":
            out.append("[^/]*")
            i += 1
        elif char == "?":
            out.append("[^/]")
            i += 1
        elif char == "[":
            end = pattern.find("]", i + 1)
            if end == -1:
                out.append(re.escape(char))
                i += 1
            else:
                out.append(pattern[i : end + 1].replace("[!", "[^"))
                i = end + 1
        else:
            out.append(re.escape(char))
            i += 1
    body = "".join(out)
    prefix = "^" if anchored else "^(?:.*/)?"
    return re.compile(prefix + body + "$")


@dataclass
class GitAttributes:
    """The `linguist-generated` rules of a repository's .gitattributes file."""

    rules: list[tuple[re.Pattern[str], bool]] = field(default_factory=list)

    @classmethod
    def parse(cls, text: str) -> GitAttributes:
        rules: list[tuple[re.Pattern[str], bool]] = []
        for raw in text.splitlines():
            line = raw.strip()
            if not line or line.startswith("#"):
                continue
            pattern, *attributes = line.split()
            for attribute in attributes:
                if attribute in ("linguist-generated", "linguist-generated=true"):
                    value = True
                elif attribute in (
                    "-linguist-generated",
                    "!linguist-generated",
                    "linguist-generated=false",
                ):
                    value = False
                else:
                    continue
                rules.append((_glob_to_regex(pattern), value))
        return cls(rules)

    def generated(self, path: str) -> bool | None:
        """True/False if a rule decides it (the last matching rule wins), else None."""
        decision = None
        for regex, value in self.rules:
            if regex.match(path):
                decision = value
        return decision


def is_generated(
    path: str,
    header: Iterable[str] | None = None,
    attributes: GitAttributes | None = None,
) -> bool:
    if attributes is not None:
        decided = attributes.generated(path)
        if decided is not None:
            return decided
    if is_generated_path(path):
        return True
    return header is not None and has_generated_header(header)
