import pytest

from revv.classify import GitAttributes, has_generated_header, is_generated, is_test_file


@pytest.mark.parametrize(
    "path",
    [
        # pytest / unittest
        "tests/test_retry.py",
        "src/app/test_models.py",
        "src/app/models_test.py",
        "conftest.py",
        "tests/conftest.py",
        "myapp/tests.py",  # Django
        "tests/helpers.py",
        "tests/fixtures/payload.json",
        "src/pkg/test/util.py",
        "tests/snapshot_tests/__snapshots__/test_app/test_blur.svg",
        # Jest / Vitest / Mocha / Playwright / Cypress
        "web/src/components/StatusBadge.test.tsx",
        "web/src/api.spec.ts",
        "src/utils/format.test.mjs",
        "apps/api/test/app.e2e-spec.ts",
        "cypress/e2e/login.cy.ts",
        "src/__tests__/Button.tsx",
        "src/__mocks__/fs.js",
        "src/__snapshots__/Button.test.tsx.snap",
        "test/index.js",
        "src/setupTests.ts",
        "spec.ts",
    ],
)
def test_test_files(path):
    assert is_test_file(path)


@pytest.mark.parametrize(
    "path",
    [
        "src/latest.py",
        "src/contest.ts",
        "security/attestation.py",
        "web/src/pages/testimonials.tsx",
        "src/testing/helpers.py",
        "src/pytest_plugin.py",
        "src/protest.js",
        "docs/testing.md",
        "src/test.py",  # not a pytest pattern on its own
        "src/latest.test-data.json",
        "web/src/components/TestimonialCard.tsx",
        "src/app/contest_results.py",
        "jest.config.js",
        "vitest.config.ts",
        "src/attest/spec_parser.py",
    ],
)
def test_not_test_files(path):
    assert not is_test_file(path)


@pytest.mark.parametrize(
    "path",
    [
        "package-lock.json",
        "web/yarn.lock",
        "pnpm-lock.yaml",
        "uv.lock",
        "poetry.lock",
        "static/app.min.js",
        "static/app.js.map",
        "api/service_pb2.py",
        "api/service_pb2_grpc.py",
        "web/src/gen/service_pb.d.ts",
        "src/__generated__/UserQuery.graphql.ts",
        "src/schema.generated.ts",
    ],
)
def test_generated_by_path(path):
    assert is_generated(path)


@pytest.mark.parametrize(
    "path", ["src/generator.py", "src/generate_docs.ts", "lockfile.py", "src/map.ts"]
)
def test_not_generated(path):
    assert not is_generated(path)


def test_generated_header():
    assert has_generated_header(["// Code generated by protoc-gen-go. DO NOT EDIT."])
    assert has_generated_header(["# This file is automatically @generated by uv."])
    assert has_generated_header(["", "/* eslint-disable */", "// This file was auto-generated"])
    assert not has_generated_header(["def generate():", "    pass"])
    lines = ["x = 1"] * 10 + ["# DO NOT EDIT"]
    assert not has_generated_header(lines)  # only the first few lines count


def test_gitattributes_linguist_generated():
    attributes = GitAttributes.parse(
        """
        # generated code
        *.pb.ts linguist-generated=true
        dist/** linguist-generated
        docs/api/*.md linguist-generated
        src/keep.min.js -linguist-generated
        *.png binary
        """
    )
    assert attributes.generated("web/proto/user.pb.ts") is True
    assert attributes.generated("dist/bundle.js") is True
    assert attributes.generated("dist/css/app.css") is True
    assert attributes.generated("docs/api/index.md") is True
    assert attributes.generated("docs/api/nested/index.md") is None
    assert attributes.generated("src/app.ts") is None
    assert is_generated("src/keep.min.js", attributes=attributes) is False
    assert is_generated("dist/bundle.js", attributes=attributes) is True
