"""Exercise revv's GitHub write paths against a private sandbox pull request.

This talks to the real GitHub API with *your* credentials, so it never runs as part of
the test suite; you have to ask for it explicitly:

    uv run scripts/live_check.py --yes

What it does in your account (the repository name is <your login>/revv-sandbox):

* First run only: creates that repository as a PRIVATE repo, adds a few files, a branch
  and a pull request, and posts one "fixture" review comment used to test resolving.
  Pull requests and submitted reviews can't be deleted through the API, so these are
  created once and reused on every later run. Delete the repository whenever you like;
  the next run recreates it.
* Every run: creates only things it deletes again (a pending review with draft comments,
  a conversation comment, a reaction) and restores what it toggles (resolved and viewed
  states) in a `finally` block, so the sandbox does not grow.

Your token needs the `repo` scope (e.g. `gh auth login`), which it already has if revv
can post comments for you.
"""

from __future__ import annotations

import asyncio
import base64
import contextlib
import itertools
import sys
from collections.abc import Awaitable, Callable

from revv.diff import LineKind, parse_patch
from revv.github.backend import GitHubBackend
from revv.github.client import GitHubClient, GitHubError, find_token
from revv.inbox import inbox_sections, load_inbox
from revv.models import PRRef, PullRequest, RepoRef, Side
from revv.session import ReviewSession

REPO_NAME = "revv-sandbox"
BRANCH = "revv-check"
FIXTURE_MARKER = "revv live-check fixture"
RUN_MARKER = "revv live-check (temporary)"

BASE_FILES = {
    "app/calc.py": '''\
"""Tiny calculator used by revv's live checks."""


def add(a: int, b: int) -> int:
    return a + b


def subtract(a: int, b: int) -> int:
    return a - b


def multiply(a: int, b: int) -> int:
    result = 0
    for _ in range(b):
        result += a
    return result


def divide(a: int, b: int) -> float:
    return a / b
''',
    "app/legacy.py": '''\
"""Old helpers, removed on the branch."""


def double(x):
    return x * 2
''',
    "tests/test_calc.py": """\
from app.calc import add


def test_add():
    assert add(1, 2) == 3
""",
}

BRANCH_FILES = {
    "app/calc.py": '''\
"""Tiny calculator used by revv's live checks."""


def add(a: int, b: int) -> int:
    return a + b


def subtract(a: int, b: int) -> int:
    return a - b


def multiply(a: int, b: int) -> int:
    return a * b


def divide(a: int, b: int) -> float:
    if b == 0:
        raise ZeroDivisionError("cannot divide by zero")
    return a / b


def power(a: int, b: int) -> int:
    return a**b
''',
    "tests/test_calc.py": """\
import pytest

from app.calc import add, divide


def test_add():
    assert add(1, 2) == 3


def test_divide_by_zero():
    with pytest.raises(ZeroDivisionError):
        divide(1, 0)
""",
    "uv.lock": "# This file is automatically @generated by uv.\nversion = 1\n",
}


class Check:
    def __init__(self) -> None:
        self.failures: list[str] = []

    async def run(self, name: str, step: Callable[[], Awaitable[None]]) -> None:
        try:
            await step()
        except Exception as error:  # report and keep going; cleanup still happens
            self.failures.append(f"{name}: {error!r}")
            print(f"  ✗ {name}: {error!r}")
        else:
            print(f"  ✓ {name}")


def expect(condition: object, message: str) -> None:
    if not condition:
        raise AssertionError(message)


async def put_file(client: GitHubClient, repo: RepoRef, path: str, text: str, branch: str) -> None:
    existing = None
    with contextlib.suppress(GitHubError):  # the file may not exist yet
        response = await client.rest(
            "GET", f"/repos/{repo.full_name}/contents/{path}", params={"ref": branch}
        )
        existing = response.json().get("sha")
    await client.rest(
        "PUT",
        f"/repos/{repo.full_name}/contents/{path}",
        json={
            "message": f"Update {path}",
            "content": base64.b64encode(text.encode()).decode(),
            "branch": branch,
            **({"sha": existing} if existing else {}),
        },
    )


async def ensure_sandbox(client: GitHubClient, login: str) -> PRRef:
    repo = RepoRef(login, REPO_NAME)
    try:
        await client.rest("GET", f"/repos/{repo.full_name}")
    except GitHubError:
        print(f"Creating private repository {repo.full_name}…")
        await client.rest(
            "POST",
            "/user/repos",
            json={
                "name": REPO_NAME,
                "private": True,
                "auto_init": True,
                "description": "Scratch repository for revv's live API checks",
            },
        )
        await asyncio.sleep(2)
    pulls = (
        await client.rest(
            "GET", f"/repos/{repo.full_name}/pulls", params={"head": f"{login}:{BRANCH}"}
        )
    ).json()
    if pulls:
        return PRRef(repo, pulls[0]["number"])
    print("Setting up the sandbox pull request…")
    for path, text in BASE_FILES.items():
        await put_file(client, repo, path, text, "main")
    main = (await client.rest("GET", f"/repos/{repo.full_name}/git/ref/heads/main")).json()
    with contextlib.suppress(GitHubError):  # the branch may exist from an interrupted setup
        await client.rest(
            "POST",
            f"/repos/{repo.full_name}/git/refs",
            json={"ref": f"refs/heads/{BRANCH}", "sha": main["object"]["sha"]},
        )
    for path, text in BRANCH_FILES.items():
        await put_file(client, repo, path, text, BRANCH)
    legacy = (
        await client.rest(
            "GET", f"/repos/{repo.full_name}/contents/app/legacy.py", params={"ref": BRANCH}
        )
    ).json()
    await client.rest(
        "DELETE",
        f"/repos/{repo.full_name}/contents/app/legacy.py",
        json={"message": "Remove legacy helpers", "sha": legacy["sha"], "branch": BRANCH},
    )
    pull = (
        await client.rest(
            "POST",
            f"/repos/{repo.full_name}/pulls",
            json={
                "title": "Sandbox pull request for revv live checks",
                "head": BRANCH,
                "base": "main",
                "body": "Used by `scripts/live_check.py` in revv. Safe to ignore.",
            },
        )
    ).json()
    return PRRef(repo, pull["number"])


def find_lines(pr: PullRequest):
    """Pick comment targets from the real patches."""
    calc = pr.file("app/calc.py")
    assert calc is not None and calc.patch
    hunks = parse_patch(calc.patch)
    added = [ln for h in hunks for ln in h.lines if ln.kind is LineKind.ADD]
    deleted = [ln for h in hunks for ln in h.lines if ln.kind is LineKind.DEL]
    # two consecutive added lines in one hunk, for a range comment
    pair = None
    for hunk in hunks:
        run = [ln for ln in hunk.lines if ln.kind is LineKind.ADD]
        for first, second in itertools.pairwise(run):
            if second.new_no == (first.new_no or 0) + 1:
                pair = (first, second)
                break
        if pair:
            break
    assert added and deleted and pair
    return added[0], deleted[0], pair


async def main() -> int:
    if "--yes" not in sys.argv[1:]:
        print(__doc__)
        print("Nothing was done. Re-run with --yes to go ahead.")
        return 2
    token = find_token()
    client = GitHubClient(token)
    backend = GitHubBackend(client)
    check = Check()
    login = (await client.graphql("query { viewer { login } }"))["viewer"]["login"]
    ref = await ensure_sandbox(client, login)
    print(f"Sandbox: {ref.web_url}")
    session = ReviewSession(backend, ref)
    pr = await session.load()

    # One submitted thread to resolve/unresolve; created once (this also checks the
    # "comment now" path: start review, add thread, submit).
    fixture = next(
        (t for t in pr.threads if t.root and FIXTURE_MARKER in t.root.body and not t.is_pending),
        None,
    )
    if fixture is None:
        added, _, _ = find_lines(pr)
        fixture = await session.add_thread(
            path="app/calc.py",
            body=f"{FIXTURE_MARKER}: kept on purpose (submitted reviews can't be deleted).",
            line=added.new_no,
            side=Side.RIGHT,
            publish_now=True,
        )
        expect(not fixture.is_pending, "fixture thread should be published")
        pr = await session.refresh()
        fixture = next(t for t in pr.threads if t.id == fixture.id)
        print("  ✓ comment now (created the fixture thread)")

    created_issue_comments: list[str] = []
    viewed_before = {f.path: f.is_viewed for f in pr.files}
    resolved_before = fixture.is_resolved
    try:
        await check.run("read: pull request, files and threads", lambda: _read(session))
        await check.run("read: inbox searches", lambda: _inbox(backend, ref.repo))
        await check.run("read: file contents", lambda: _contents(session))
        await check.run("viewed: batch mark and unmark", lambda: _viewed(session))
        await check.run(
            "pending review: threads, replies, edit, delete, discard", lambda: _pending(session)
        )
        await check.run("resolve and unresolve", lambda: _resolve(session, fixture.id))
        await check.run(
            "conversation comment: post, edit, resolve, unresolve, delete",
            lambda: _issue_comment(session, created_issue_comments),
        )
        await check.run("reactions: add and remove", lambda: _reaction(session, fixture.id))
    finally:
        print("Cleaning up…")
        await _cleanup(session, created_issue_comments, viewed_before, fixture.id, resolved_before)
        await backend.aclose()
    if check.failures:
        print(f"\n{len(check.failures)} check(s) failed")
        return 1
    print("\nAll live checks passed.")
    return 0


async def _read(session: ReviewSession) -> None:
    pr = await session.refresh()
    paths = {f.path for f in pr.files}
    expect(
        {"app/calc.py", "app/legacy.py", "tests/test_calc.py", "uv.lock"} <= paths,
        f"files: {paths}",
    )
    for file in pr.files:
        expect(file.patch, f"{file.path} has no patch")
    legacy = pr.file("app/legacy.py")
    expect(legacy is not None and legacy.status.value == "removed", "legacy.py should be removed")


async def _inbox(backend: GitHubBackend, repo: RepoRef) -> None:
    sections = inbox_sections(repo)
    await load_inbox(backend, sections)
    errors = [f"{s.key}: {s.error}" for s in sections if s.error]
    expect(not errors, f"inbox errors: {errors}")
    mine = next(s for s in sections if s.key == "mine")
    expect(mine.items, "own sandbox PR should be in 'Mine'")


async def _contents(session: ReviewSession) -> None:
    pr = session.pr
    texts = await session.new_texts(pr.files)
    expect("def power" in (texts.get("app/calc.py") or ""), "head text of calc.py")
    expect(texts.get("app/legacy.py") is None, "removed file has no head text")


async def _viewed(session: ReviewSession) -> None:
    pr = session.pr
    files = [f for f in pr.files if not f.is_viewed][:2]
    expect(files, "need unviewed files")
    await session.set_viewed_many(files, True)
    fresh = await session.refresh()
    refreshed = [fresh.file(f.path) for f in files]
    for file, now in zip(files, refreshed, strict=True):
        expect(now is not None and now.is_viewed, f"{file.path} should be viewed")
    await session.set_viewed_many([f for f in refreshed if f is not None], False)
    fresh = await session.refresh()
    for file in files:
        now = fresh.file(file.path)
        expect(now is not None and not now.is_viewed, f"{file.path} should be unviewed")


async def _pending(session: ReviewSession) -> None:
    pr = session.pr
    expect(pr.pending_review is None, "no pending review expected at the start")
    added, deleted, (first, second) = find_lines(pr)
    line = await session.add_thread(
        path="app/calc.py", body=f"{RUN_MARKER}: line", line=added.new_no, side=Side.RIGHT
    )
    expect(line.is_pending and pr.pending_review is not None, "thread should be pending")
    ranged = await session.add_thread(
        path="app/calc.py",
        body=f"{RUN_MARKER}: range\n\n```suggestion\n{first.text}\n{second.text}\n```",
        line=second.new_no,
        side=Side.RIGHT,
        start_line=first.new_no,
        start_side=Side.RIGHT,
    )
    old_side = await session.add_thread(
        path="app/calc.py", body=f"{RUN_MARKER}: old side", line=deleted.old_no, side=Side.LEFT
    )
    removed = await session.add_thread(
        path="app/legacy.py", body=f"{RUN_MARKER}: removed file", line=4, side=Side.LEFT
    )
    file_level = await session.add_thread(
        path="tests/test_calc.py", body=f"{RUN_MARKER}: file", file_level=True
    )
    reply = await session.reply(line, f"{RUN_MARKER}: reply")
    expect(reply.is_pending, "reply should be pending")
    await session.edit_comment(reply, f"{RUN_MARKER}: reply (edited)")

    fresh = await session.refresh()
    by_id = {t.id: t for t in fresh.threads}
    expect(fresh.pending_comment_count == 6, f"pending comments: {fresh.pending_comment_count}")
    got = by_id[ranged.id]
    expect(
        (got.start_line, got.line) == (first.new_no, second.new_no),
        f"range: {got.start_line}-{got.line}",
    )
    expect(
        by_id[old_side.id].side is Side.LEFT and by_id[old_side.id].line == deleted.old_no,
        "old side",
    )
    expect(by_id[removed.id].side is Side.LEFT, "removed file thread side")
    expect(by_id[file_level.id].is_file_level, "file-level thread")
    edited = by_id[line.id].comments[-1]
    expect(edited.body.endswith("(edited)"), "edited reply body")

    await session.delete_comment(edited)
    expect(len(by_id[line.id].comments) == 1, "reply deleted")
    await session.discard_pending_review()
    expect(not any(t.has_pending for t in session.pr.threads), "local state is clean")
    # GitHub removes the threads of a deleted review asynchronously: poll briefly.
    for _ in range(10):
        fresh = await session.refresh()
        leftovers = [t for t in fresh.threads if t.root and RUN_MARKER in t.root.body]
        if fresh.pending_review is None and not leftovers:
            break
        await asyncio.sleep(1)
    expect(fresh.pending_review is None, "pending review discarded")
    expect(not leftovers, f"leftover threads: {len(leftovers)}")


async def _resolve(session: ReviewSession, thread_id: str) -> None:
    thread = next(t for t in session.pr.threads if t.id == thread_id)
    target = not thread.is_resolved
    await session.set_resolved(thread, target)
    fresh = await session.refresh()
    expect(next(t for t in fresh.threads if t.id == thread_id).is_resolved == target, "toggled")
    thread = next(t for t in fresh.threads if t.id == thread_id)
    await session.set_resolved(thread, not target)
    fresh = await session.refresh()
    expect(
        next(t for t in fresh.threads if t.id == thread_id).is_resolved == (not target), "restored"
    )
    # a pending reply to a submitted thread, then discarded
    thread = next(t for t in fresh.threads if t.id == thread_id)
    await session.reply(thread, f"{RUN_MARKER}: pending reply")
    await session.discard_pending_review()


async def _issue_comment(session: ReviewSession, created: list[str]) -> None:
    comment = await session.add_issue_comment(f"{RUN_MARKER}: conversation comment")
    created.append(comment.id)
    await session.edit_comment(comment, f"{RUN_MARKER}: conversation comment (edited)")
    edited = next(c for c in session.pr.comments if c.id == comment.id)
    await session.set_comment_resolved(edited, True)
    fresh = await session.refresh()
    got = next(c for c in fresh.comments if c.id == comment.id)
    expect(got.is_resolved, f"minimized as resolved: {got.is_minimized} {got.minimized_reason}")
    await session.set_comment_resolved(got, False)
    fresh = await session.refresh()
    got = next(c for c in fresh.comments if c.id == comment.id)
    expect(not got.is_minimized, "unminimized")
    await session.delete_comment(got)
    created.remove(comment.id)


async def _reaction(session: ReviewSession, thread_id: str) -> None:
    thread = next(t for t in session.pr.threads if t.id == thread_id)
    root = thread.root
    assert root is not None
    await session.toggle_reaction(root, "ROCKET")
    fresh = await session.refresh()
    root = next(t for t in fresh.threads if t.id == thread_id).root
    assert root is not None
    rocket = next((r for r in root.reactions if r.content == "ROCKET"), None)
    expect(rocket is not None and rocket.viewer_has_reacted, "reaction added")
    await session.toggle_reaction(root, "ROCKET")


async def _cleanup(
    session: ReviewSession,
    created_issue_comments: list[str],
    viewed_before: dict[str, bool],
    fixture_id: str,
    resolved_before: bool,
) -> None:
    backend = session.backend
    try:
        pr = await session.refresh()
    except Exception as error:
        print(f"  ! couldn't reload for cleanup: {error!r}")
        return
    steps: list[tuple[str, Awaitable[object]]] = []
    if pr.pending_review is not None:
        steps.append(("discard pending review", backend.delete_review(pr.pending_review.id)))
    for comment in pr.comments:
        if comment.id in created_issue_comments or (
            RUN_MARKER in comment.body and comment.viewer_can_delete
        ):
            steps.append(("delete conversation comment", backend.delete_issue_comment(comment.id)))
    for thread in pr.threads:
        for comment in thread.comments:
            if RUN_MARKER in comment.body and comment.viewer_can_delete:
                steps.append(("delete review comment", backend.delete_review_comment(comment.id)))
            for reaction in comment.reactions:
                if reaction.viewer_has_reacted and thread.id == fixture_id:
                    steps.append(
                        (
                            "remove reaction",
                            backend.set_reaction(comment.id, reaction.content, False),
                        )
                    )
        if thread.id == fixture_id and thread.is_resolved != resolved_before:
            steps.append(
                ("restore resolved state", backend.set_thread_resolved(thread.id, resolved_before))
            )
    viewed = [f.path for f in pr.files if f.is_viewed and not viewed_before.get(f.path, False)]
    unviewed = [f.path for f in pr.files if not f.is_viewed and viewed_before.get(f.path, False)]
    if viewed:
        steps.append(("restore viewed state", backend.set_viewed_many(pr, viewed, False)))
    if unviewed:
        steps.append(("restore viewed state", backend.set_viewed_many(pr, unviewed, True)))
    for label, step in steps:
        try:
            await step
            print(f"  · {label}")
        except Exception as error:
            print(f"  ! {label} failed: {error!r}")


if __name__ == "__main__":
    sys.exit(asyncio.run(main()))
